version: '3.1'

services:

  # api:
  #   build: ./
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     MONGODB_URI: mongodb://mongo:27017/Zoo
  #     MANGODB_USER: root
  #     MANGODB_PASSWORD: passwordRoot
  #     PORT: 3000

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwordRoot
  